### ISSUE TITLE
Add UnityUtil features to Unreal

### ISSUE THREAD

**Issue by mosment3DRepo** [3drepo/Product#1]
### Description

In order for Unreal to be pixel streamed and used in the PlanBase platform we need to port some of the 3D Repo Unity APIs to Unreal

### Goals
Have the following API equivalents available in Javascript when Unreal is pixel streamed
- [ ] UnityUtil.setAPIHost
- [ ] UnityUtil.resetCamera
- [ ] UnityUtil.setViewpoint
- [ ] UnityUtil.overrideMeshColor
- [ ] UnityUtil.overrideMeshOpacity
- [ ] UnityUtil.toggleVisibility
- [ ] UnityUtil.resetMeshColor
- [ ] UnityUtil.resetMeshOpacity
- [ ] UnityUtil.dropIssuePin
- [ ] UnityUtil.pickPointAlert (note, this is a callback function that is triggered by ExternCaller inside unity)

**Comment by sebjf** [comment]
(I will put my notes about the scoping in this comment, and update them as I answer questions as I go..)

Use Case: An Unreal process will run the viewer, receiving inputs from the user.

# Immediate Unknowns

How many users can a single Unreal process support?
How do Unreal viewers and the backend communicate?

# PlanBase requisite APIs

 UnityUtil.setAPIHost
 
Straightforward. Its implementation depends on the JS->Backend functionality provided by Pixel Streaming.
 
 UnityUtil.resetCamera
 
Straightforward, presuming we write the camera controller code.
 
 UnityUtil.setViewpoint
 
Straightforward.

Do the parameters for the setViewport line up?
Are the viewport parameters relative to the same coordinate system?
 
 UnityUtil.overrideMeshColor

Straightforward. Already implemetned by the examples. 

 UnityUtil.overrideMeshOpacity
 
Complex. Currently we manage which queue supermeshes are drawn to. It is not clear how this could be done in Unreal. We may need to investigate moving geometry on the CPU between meshes. We can make robust performance estimates as we will control the hardware the backend runs on.
 
 UnityUtil.toggleVisibility
 
Straightforward. This should be a simple shader option.
Is it a simple shader option?
 
 UnityUtil.resetMeshColor 
 UnityUtil.resetMeshOpacity

Straightforward. (The inverse of the above operations)
 
 UnityUtil.dropIssuePin
 
Complex. We need to re-create the pins functionality in Unreal. Picking already works, but we need to create the assets for the Pins and the logic to manage them. The visibility control will be tricky since we don't have easy access to the maps the same way we do in Unity.
 
 UnityUtil.pickPointAlert (note, this is a callback function that is triggered by ExternCaller inside unity)
 
 Straightforward, depending on the JS/backend mechanism.
 
 
# Additional Functionality

## Camera

We will need to build a camera controller based on the Unity behaviour.

**Comment by carmenfan** [comment]
@sebjf  do whatever works for you, but once you've gathered all the thoughts create the issue in the unreal repo please 😆
